### ISSUE TITLE
2024 07 27 bug

### ISSUE THREAD

**Issue by kkh725** [team-echoist/android#24]
1.
07 27 23시 15분 
@GET("api/support/settings/{deviceId}") 
글 조회 알림 요청하는 api에서 에러 발생
![image](https://github.com/user-attachments/assets/5cc29da9-90a4-405b-852b-f0e2a6dc9bee)
 
device id :  db0f6f5cf9035cfb
token : 
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTEsImlhdCI6MTcyMjA5MDA0MiwiZXhwIjoxNzI0NjgyMDQyfQ.vATUbuDgMqCTiJ5FfkbGCYijMZmmG48HtiaI3vHG8GM

2.
글로키 api 요청시 500 에러 (사진업로드필요?)
    @GET("api/home/guleroquis")

**Comment by maxisneverthat** [comment]
제 예상으로, 탈퇴처리된 회원 아이디로 디바이스 아이디를 가지고있는게 아닌가 하는 의심이 드는군여.. 탈퇴처리에 저 디바이스 아이디를 날러벼리는 로직을 추가하던가 해봐야겟네영. 아니면 단순하게 디바이스아이디 필드 중복을 허용하고 유저아이디와 묶어서 조회한다던가..?

**Comment by maxisneverthat** [comment]
#317
