### ISSUE TITLE
[Bug] 스토리 생성 시 에세이조회, 이전글(profile)요청시 api issue

### ISSUE THREAD

**Issue by kkh725** [team-echoist/android#28]
1. 스토리 생성 시 스토리에 넣을 에세이를 조회할 경우
@GET  api/stories/related 
Linked out 된 에세이들이 포함되어 나오는 이슈.

2. 나의 글(에세이) 상세조회 시 another essay를 응답에서 받고있는데 
type으로 'profile' 요청시 public 과 private이 구분없이 들어오는 issue
@GET("api/essays/{essayId}")

**Comment by maxisneverthat** [comment]
1번 해결

**Comment by maxisneverthat** [comment]
https://github.com/team-echoist/server/pull/371
