### ISSUE TITLE
[BUG] 약관동의 후 화면 다음 동작이 안되는 이슈

### ISSUE THREAD

**Issue by Lee-Jun-Young** [team-echoist/android#68]
약관동의 체크를 하고 확인 버튼을 눌러도 다음 동작이 되지 않는 이슈
아래 로그처럼 저장은 성공적으로 이루어지는데, 그 이후에 동작을 하는 코드가 없는 상황.

<img src="https://github.com/user-attachments/assets/c9cb080f-617e-4ab2-a62f-f745d93c34c2" height="300"/>

**Comment by kkh725** [comment]
<img width="841" alt="image" src="https://github.com/user-attachments/assets/bef156e6-0daa-48e3-913d-49ed838d79c8">

제가 그때 누락되어있던 navigateToComplete변수를 모바일에만 적용시킨것 같습니다. 태블릿 코드에서 

```
val navigateToComplete by viewModel.navigateToComplete.collectAsState()

    LaunchedEffect(navigateToComplete) {
        if (navigateToComplete) {
            navController.navigate(Routes.SignUpComplete)
            viewModel.onNavigated()
        }
    }
   ```

이런식으로 화면이동 코드 추가하시면 동작 될 것 같습니다!
signUpViewModel 의 navcontroller 제거작업중에 화면이동하는 부분을 View에 추가하지 않았던 것 같네요.

**Comment by kkh725** [comment]
아 변수명은 navigateToComplete에서 api동작을 나타내는 변수명으로 고치면좋을거같네여!
