### ISSUE TITLE
[BUG] 인증번호 바텀시트 

### ISSUE THREAD

**Issue by Lee-Jun-Young** [team-echoist/android#78]
## 어떤 버그인가요?

> 인증번호 요청 다중클릭이 가능한 버그. 

## 어떤 상황에서 발생한 버그인가요?

> 회원가입, 이메일 주소 변경 등의 기능에서 인증번호 요청을 하는 기능이 있는데 다중클릭으로 API도 다중호출되고 바텀시트도 여러개 올라옴..

## 예상 결과

> API 한번 호출과 바텀시트 1개 노출

**Comment by kkh725** [comment]
https://github.com/user-attachments/assets/9ccb89b2-c547-4b98-8f1b-5646dec6dae2

모바일에서는 버튼 클릭 후 -> api 응답완료될때까지 버튼을 비활성화 되게끔 만들었어여 
혹시 어느부분이 문제인걸까요?

**Comment by Lee-Jun-Young** [comment]
여러번도 눌러보셨나요????
