### ISSUE TITLE
[BUG] 글로키 다이얼로그 

### ISSUE THREAD

**Issue by Lee-Jun-Young** [team-echoist/android#81]
## 어떤 버그인가요?

>오늘의 글로키가 도착했어요! 다이얼로그가 홈화면으로 이동할때마다 매번 나옴.

## 어떤 상황에서 발생한 버그인가요?

>화면이동을 하고 다시 홈 화면으로 돌아왔을 때 발생

## 예상 결과

>오늘의 글로키가 도착했어요 다이얼로그는 앱 실행 시 최초 한번 뜨는 게 자연스럽지않나 생각합니다. 
혹시 의도된 바라면 이슈 닫도록 하겠습니다!

**Comment by kkh725** [comment]
아..
```
visible = viewModel.isVisibleGeulRoquis && !viewModel.isFirstUser,
```
뷰모델 변수로 글로키 visible상태를 관리했었는데 분명 한번만 나왔는데 왜 매번나오지 했는데 

```
@Composable
fun HomePage(
    navController: NavController,
    viewModel: HomeViewModel = hiltViewModel(), //힐트뷰모델 입혀서 그런거였네요..
    writingViewModel: WritingViewModel,
    statusCode: Int
)
```
앱 실행시 최초한번 뜨는게 맞습니당.
