### ISSUE TITLE
[BUG] 세션 만료 의견

### ISSUE THREAD

**Issue by Lee-Jun-Young** [team-echoist/android#83]
## 어떤 버그인가요?

>세션만료 확인누르면 로그아웃 처리에 대한 의견제시입니다.

## 어떤 상황에서 발생한 버그인가요?

>세션만료화면이 나왔을 때 확인을 눌러 로그인 화면으로 가고 다시 앱을 실행시켰을 때 세션만료 화면이 다시 뜨는 현상

## 예상 결과

>세션만료화면에서 확인을 눌렀을 때 로그아웃 처리가 되는 것이 자연스럽지 않나 생각합니다.

## 참고할만한 자료(선택)

https://github.com/user-attachments/assets/22d2b58e-da3f-49b0-83b5-505690eb8b34

**Comment by kkh725** [comment]
```
return when {
            isAutoLoginClicked && isDateAfterToday(tokenValidTime) -> {
                Token.accessToken = tokens.accessToken
                Token.refreshToken = tokens.refreshToken
                "${Routes.Home}/200"
            }

            isOnboardingFinished -> Routes.LoginPage
            else -> Routes.OnBoarding
        }
```
현재 이런식으로 앱의 startDestination이 구현되어 있는데요, 
아마 로그인 화면에서는 세션만료 UI가 안나타납니다.

```isAutoLoginClicked && isDateAfterToday(tokenValidTime)``` 의 조건이 때문에 세션이 만료되었는데도 불구하고 앱을 재실행 시에 로그인화면이 아닌 홈화면으로 바로 진입하는 것 같습니다.

소셜로그인 또는 로컬로그인을 진행할 때
```
userDataRepository.saveRefreshTokenValidTime(
                            calculateDateAfter30Days()
                        ) // 토큰 유효 기간 저장
```
                       
리프래시토큰의 유효기간을 30일로 지정을 해놨었네요.
생각해보니 이걸 바꿀 필요는 없을 것 같고

그냥 간단하게 세션 만료 확인 누르면 isAutoLoginClicked -> false 로 지정해서 로그인화면으로 이동하게끔 하면 되지않을까 싶습니다 !!
